/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 house.gltf 
Author: GeorgeZemtsov (https://sketchfab.com/weses)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hello-neighbor-prototype-house-floor-1-8cd7a70da53e45d9baf60e7517a9a2a7
Title: Hello Neighbor Prototype House Floor 1
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/house.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.HouseMesh_map_floor_1_mo_dummy_material_0_0.geometry} material={materials.dummy_material_0} />
          <mesh geometry={nodes.HouseMesh_map_floor_1_mo_dummy_material_1_0.geometry} material={materials.dummy_material_1} />
          <mesh geometry={nodes.HouseMesh_map_floor_1_mo_dummy_material_2_0.geometry} material={materials.dummy_material_2} />
          <mesh geometry={nodes.HouseMesh_map_floor_1_mo_dummy_material_3_0.geometry} material={materials.dummy_material_3} />
          <mesh geometry={nodes.HouseMesh_map_floor_1_mo_dummy_material_4_0.geometry} material={materials.dummy_material_4} />
        </group>
        <mesh geometry={nodes.Rails_Railings_0.geometry} material={materials.Railings} position={[392.379, 290.396, -644.196]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/house.gltf')
